# Generated by Django 4.1.6 on 2023-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_modified_date_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(null=True, to='blog.label'),
        ),
    ]
