# Generated by Django 4.1.6 on 2023-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='labels',
            field=models.ManyToManyField(blank=True, to='blog.label'),
        ),
    ]
